### ISSUE TITLE
Detect Phantom crash

### ISSUE THREAD

**Issue by gkorland** [baudehlo/node-phantom-simple#12]
I keep getting the following crash on Linux:

```
09:11:03.887 phantom stderr: PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/106608aa-64f2-37ce-6b453bd7-6876263f.dmp

09:11:04.011 Request() error evaluating open() call: Error: socket hang up
09:11:04.012 Poll Request error: Error: socket hang up
```

1. Is there a way to detect it? 
2. Is there a way to restart Phantom?

**Comment by RavenHursT** [comment]
So.. I set out to try this today.. but it appears as though node-phantom-simple isn't sending the data on through to the handler.

I have this in my code:

````javascript
        phantomInstance.process.stderr.on('data', function(data) {
            if (data.indexOf('PhantomJS has crashed') !== -1) {
                console.log('CRASH!!!!!');
            }
        });
````

But I'm getting undefined for ```data```:

````
phantom stderr: PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/8C72FB0A-299F-4626-A114-180D6E2395F8.dmp

TypeError: undefined is not a function
    at Socket.<anonymous> ([line and column where data.indexOf() is being called])
    at Socket.emit (events.js:129:20)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at Pipe.onread (net.js:538:20)
````

**Comment by puzrin** [comment]
That seems to be fixed in master.  If browser crash, driver will return error on any call. We also did `HeadlessError` class for this kind of errors.

Closing?

**Comment by RavenHursT** [comment]
Can you give a quick example on how to utilize the ```HeadlessError``` class that you're referring to?

**Comment by puzrin** [comment]
Consider it as usual error, returned in callback.

**Comment by puzrin** [comment]
@RavenHursT can you clarify problem? Do you need just to get error in callback, or know exactly that error was because of engine crash (process unavailable)?

In any case, process restart should NOT be done by this driver, IMHO. Current situation is:

- callbacks do not hang, if phantom died. You will get error.
- there are no flags/events to know exactly error reason, but you can scan error message for "died" pattern https://github.com/baudehlo/node-phantom-simple/blob/master/node-phantom-simple.js#L494

Is is enougth? We could add event "died", but is it really needed?

**Comment by RavenHursT** [comment]
No.. this all seems to be working now.  Thanks!  I think this can be closed now.. :+1:
