### ISSUE TITLE
Casperjs?

### ISSUE THREAD

**Issue by braco** [baudehlo/node-phantom-simple#23]
What are the chances of this supporting Casper?

That would make this the #1 scraping suite under node, by far.

All of that syntactic sugar provided by Casper would be a huge boost.

**Comment by puzrin** [comment]
@braco this request seems to be out of project scope. This is a driver, and you ask about framework. Take a look at this repos:

- https://github.com/johntitus/node-horseman
- https://github.com/nodeca/navit
- https://github.com/segmentio/nightmare
- https://github.com/assaf/zombie

2 first from this list are based on this diver.

**Comment by laggingreflex** [comment]
[CasperJS allows being loaded from within PhantomJS:](http://docs.casperjs.org/en/latest/faq.html#can-i-use-casperjs-without-using-the-casperjs-executable)

I was able to get it to work with [Phridge] since it has a [`.run`][2] function which runs any function directly inside PhantomJS environment, where you can do the above easily. 

    casperPath = path.join(require.resolve('casperjs/bin/bootstrap'), '/../..');
    phantom.run(casperPath, function(casperPath) {
        phantom.casperPath = casperPath;
        phantom.injectJs(casperPath + '/bin/bootstrap.js');
        ...


[Phridge]: https://github.com/peerigon/phridge
[2]: https://github.com/peerigon/phridge#run-any-function-inside-phantomjs
